name: Angular CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Packages
        run: npm install
        working-directory: ./project # Tells GitHub to go inside your 'project' folder first

      - name: Build App
        run: npm run build -- --base-href /ci-cd/
        working-directory: ./project

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Path based on your image: top-folder/project-folder/dist/project-folder/browser
          publish_dir: ./project/dist/project/browser